DROP TABLE banco.CLIENTE2;

CREATE TABLE banco.CLIENTE2
(ID             INT(11) NOT NULL AUTO_INCREMENT,
 NOME           VARCHAR(30), 
 SEXO           CHAR(1),
 IDADE          TINYINT(1),
 NEWS_LETTER    TINYINT(1),
 CONSTRAINT CLIENTE2_ID_PK PRIMARY KEY (id),
 CONSTRAINT CLIENTE2_NOME_NN CHECK (NOME IS NOT NULL)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Jose Roberto', 'M', 1, 0);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Joana Rocha', 'F', 3, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Vinicius Ribeiro', 'M', 2, 0);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Pedro Arnaldo', 'M', 1, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Teresa Rosa', 'F', 2, 0);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Rogerio Senna', 'M', 3, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Mirza Roman', 'F', 2, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Sonia Albuquerque', 'F', 3, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Luis Carlos Rosa', 'M', 2, 0);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Vitor Cerqueira', 'M', 1, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Rosana Lima', 'F', 1, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Samuel Santana', 'M', 1, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Paula Monteiro', 'F', 3, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Izabela Moreira', 'F', 2, 0);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Celia Marques', 'F', 3, 1);

INSERT INTO CLIENTE2(NOME, SEXO, IDADE, NEWS_LETTER)
VALUES('Ridualdo Monteiro', 'F', 2, 1);

UPDATE CLIENTE2 SET NOME = UPPER(NOME);

COMMIT;
