DROP USER SWING8 CASCADE;
CREATE USER SWING8 IDENTIFIED BY SWING8;
GRANT CONNECT, RESOURCE TO SWING8;

CONNECT SWING8/SWING8

DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CLIENTE;

CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CLIENTE
(NUMERO         NUMBER(5)
   CONSTRAINT CLIENTE_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT CLIENTE_NOME_NN
   NOT NULL,
 SEXO           CHAR(1)
   CONSTRAINT CLIENTE_SEXO_NN
   NOT NULL,
 IDADE          NUMBER(1)
   CONSTRAINT CLIENTE_IDADE_NN
   NOT NULL,
 NEWS_LETTER    NUMBER(1));

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Jose Roberto', 'M', 1, 0);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Joana Rocha', 'F', 3, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Vinicius Ribeiro', 'M', 2, 0);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Pedro Arnaldo', 'M', 1, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Teresa Rosa', 'F', 2, 0);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Rogério Senna', 'M', 3, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Mirza Roman', 'F', 2, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Sonia Albuquerque', 'F', 3, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Luis Carlos Rosa', 'M', 2, 0);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Vitor Cerqueira', 'M', 1, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Rosana Lima', 'F', 1, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Samuel Santana', 'M', 1, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Paula Monteiro', 'F', 3, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Izabela Moreira', 'F', 2, 0);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Celia Marques', 'F', 3, 1);

INSERT INTO CLIENTE(NUMERO, NOME, SEXO, IDADE, NEWS_LETTER)
VALUES(SEQ_CLIENTE.NEXTVAL, 'Ridualdo Monteiro', 'F', 2, 1);

UPDATE CLIENTE SET NOME = UPPER(NOME);

COMMIT;
