DROP USER JPA1 CASCADE;
CREATE USER JPA1 IDENTIFIED BY JPA1;
GRANT CONNECT, RESOURCE TO JPA1;

CONNECT JPA1/JPA1

DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PRODUTO;

CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT PRODUTO_NOME_NN
   NOT NULL,
 LANCE_MINIMO  NUMBER(8,2)
   CONSTRAINT PRODUTO_LANCE_MINIMO_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT PRODUTO_DATA_CADASTRO_NN
   NOT NULL,
 DATA_VENDA     DATE);

INSERT INTO PRODUTO(ID, NOME, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 2000, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 22 POL', 2500, SYSDATE);

COMMIT;
