Acrescente no arquivo C:\Program Files (x86)\PostgreSQL\8.0\data\pg_hba.conf a linha abaixo:

host    all         all        192.168.0.0/16         md5

Supondo que o endereço ip da sua máquina começa com 192.168.


-- DROP TABLE PRODUTO CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_PRODUTO;

CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE PRODUTO
(ID             NUMERIC(5,0)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR(30) 
   CONSTRAINT PRODUTO_NOME_NN
   NOT NULL,
 LANCE_MINIMO  NUMERIC(8,2)
   CONSTRAINT PRODUTO_LANCE_MINIMO_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT PRODUTO_DATA_CADASTRO_NN
   NOT NULL,
 DATA_VENDA     DATE);

INSERT INTO PRODUTO(ID, NOME, LANCE_MINIMO, DATA_CADASTRO)
VALUES(NEXTVAL('SEQ_PRODUTO'), 'TV SAMSUNG 20 POL', 2000, '2008-01-20');

INSERT INTO PRODUTO(ID, NOME, LANCE_MINIMO, DATA_CADASTRO)
VALUES(NEXTVAL('SEQ_PRODUTO'), 'TV SAMSUNG 22 POL', 2500, '2009-02-20');

COMMIT;
